import os
import re
from datetime import datetime


class TestFileWriter:
    """
    Step 3: Saves AI-generated test code to a .py file.
    Organises files by timestamp so each run is separate.
    """

    OUTPUT_DIR = "output/generated_tests"

    def __init__(self):
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)

    def save(self, code, page_name):
        """
        Save generated test code to a .py file.
        Returns path to saved file.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename  = f"test_{page_name}_{timestamp}.py"
        filepath  = os.path.join(self.OUTPUT_DIR, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(self._add_header(code, page_name))

        print(f"[TestFileWriter] Saved: {filepath}")
        return filepath

    def _add_header(self, code, page_name):
        """Add a file header comment to the generated test file"""
        header = f"""# ═══════════════════════════════════════════════════════
# AUTO-GENERATED TEST FILE
# Generated by: AI-Powered Test Generator
# Page: {page_name}
# Generated at: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# Tool: Playwright + Gemini AI + Python
# NOTE: Review and adjust selectors before running
# ═══════════════════════════════════════════════════════

"""
        return header + code

    def read(self, filepath):
        """Read and return contents of a test file"""
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()

    def list_generated(self):
        """List all generated test files"""
        return [
            os.path.join(self.OUTPUT_DIR, f)
            for f in os.listdir(self.OUTPUT_DIR)
            if f.endswith(".py")
        ]
